import type { TimelineSource } from "./types";

const OLD_MAPS = "https://commons.wikimedia.org/wiki/Category:Old_maps_of_Bengaluru";
const ZENODO_SOI = "https://zenodo.org/records/8388121";

function cityPlan(year: number, when: string): TimelineSource {
  return {
    id: `city-plan-${year}`,
    from: year,
    when,
    title: "Cantonment and city plan",
    holder: "Wikimedia Commons, old maps of Bengaluru",
    kind: "map",
    tells: "The large central tanks, by name.",
    coverage: "The city only",
    licence: "Public domain",
    status: "found",
    links: [{ label: "Open the old maps of Bengaluru", href: OLD_MAPS }],
  };
}

export const MAPS: TimelineSource[] = [
  {
    id: "mackenzie-survey",
    from: 1799,
    to: 1808,
    when: "1799 to 1808",
    title: "Colin Mackenzie's Mysore Survey, 2 miles to an inch",
    holder: "British Library",
    kind: "map",
    tells: "Where the tanks were, with the villages and the land they watered.",
    coverage: "The whole area",
    licence: "Not known",
    status: "not-public",
    access: "No public scans found",
    links: [],
  },
  {
    id: "ross-1800",
    from: 1800,
    when: "1800",
    title: "James Ross, survey of the boundaries of Purgunna of Bangalore",
    holder: "British Library, via Wikimedia Commons",
    kind: "map",
    tells: "It may show tanks; nobody has checked the image for them yet.",
    coverage: "Most of both districts",
    licence: "CC BY-SA 4.0",
    status: "found",
    access: "Georeferenced in Wikimaps Warper",
    links: [
      {
        label: "Open the map",
        href: "https://commons.wikimedia.org/wiki/File:Survey_of_the_boundaries_of_Purgunna_of_Bangalore_(1800).png",
      },
    ],
  },
  cityPlan(1843, "1843"),
  cityPlan(1854, "1854"),
  {
    id: "soi-taluk-1878",
    from: 1878,
    when: "1878",
    title: "Map of the Bangalore Taluk",
    holder: "Survey of India, via Wikimedia Commons",
    kind: "map",
    tells: "Tank outlines; the names are likely unreadable at this scan size.",
    coverage: "The old Bangalore taluk",
    licence: "Public domain",
    status: "found",
    access: "Georeferenced",
    links: [{ label: "Open the map", href: "https://commons.wikimedia.org/wiki/File:Bangalore_map_1878.png" }],
  },
  cityPlan(1900, "About 1900"),
  {
    id: "soi-1914",
    from: 1914,
    to: 1917,
    when: "1914 to 1917",
    title: "Survey of India one-inch sheets 57G/4, 57G/8, 57G/16, 57H/5, 57H/6, 57H/7 and 57H/10",
    holder: "Survey of India, via Zenodo",
    kind: "map",
    tells: "Tank outlines and embankments, most of them unnamed.",
    coverage: "7 of the 10 Bangalore District sheets: Nelamangala, Hoskote, Kengeri and Anekal, not the two city sheets",
    licence: "CC BY 4.0",
    status: "found",
    links: [{ label: "Open the sheets on Zenodo", href: ZENODO_SOI }],
  },
  {
    id: "revenue-maps-1915",
    from: 1915,
    when: "1915",
    title: "Revenue village maps",
    holder: "Karnataka Land Records, via Wikimedia Commons",
    kind: "map",
    tells: "Every tank in a village, by survey number.",
    coverage: "One village found so far",
    licence: "Public domain",
    status: "found",
    access: "Bulk access unconfirmed",
    links: [
      {
        label: "Open the one sample",
        href: "https://commons.wikimedia.org/wiki/File:Singapura_revenue_village_map_from_1915CE.jpg",
      },
    ],
  },
  {
    id: "soi-1927",
    from: 1927,
    when: "1927",
    title: "Survey of India one-inch sheet 57 G/12",
    holder: "Survey of India, via Wikimedia Commons",
    kind: "map",
    tells: "Whether a lake was drawn on the map in 1927.",
    coverage: "Both districts, with the 1945 and 1955 sheets",
    licence: "Public domain",
    status: "on-site",
    links: [{ label: "Open sheet 57 G/12", key: "soi-57g12-1927" }],
  },
  {
    id: "soi-1945",
    from: 1945,
    when: "1945",
    title: "Survey of India one-inch sheet 57 H/9",
    holder: "Survey of India, via Wikimedia Commons",
    kind: "map",
    tells: "Whether a lake was drawn on the map in 1945.",
    coverage: "Both districts, with the 1927 and 1955 sheets",
    licence: "Public domain",
    status: "on-site",
    links: [{ label: "Open sheet 57 H/9", key: "soi-57h9-1945" }],
  },
  {
    id: "ams-1955",
    from: 1955,
    when: "1955",
    title: "U.S. Army Map Service sheets, 1:250,000",
    holder: "U.S. Army Map Service, via Wikimedia Commons",
    kind: "map",
    tells: "Whether a lake was drawn on the map in 1955, compiled from Survey of India maps of 1945-46.",
    coverage: "Both districts, with the 1927 and 1945 sheets",
    licence: "Public domain",
    status: "on-site",
    links: [
      { label: "Open sheet ND 43-12 Tumkur", key: "ams-nd43-12-1955" },
      { label: "Open sheet ND 43-16 Mysore", key: "ams-nd43-16-1955" },
      { label: "Open sheet ND 44-13 Bangalore", key: "ams-nd44-13-1955" },
      { label: "Open sheet ND 44-9 Kolar", key: "ams-nd44-9-1955" },
    ],
  },
  {
    id: "soi-1973",
    from: 1973,
    to: 1980,
    when: "1973 to 1980",
    title: "Survey of India one-inch sheets, later editions",
    holder: "Survey of India, via Zenodo",
    kind: "map",
    tells: "Each tank's surveyed outline and name.",
    coverage:
      "Every Bangalore District sheet: 57G/4 (1973), 57G/7 (1975), 57G/8 (1974), 57G/12 (1978), 57G/16 (1974), 57H/5 (1973), 57H/6 (1973), 57H/7 (1979), 57H/9 (1980) and 57H/10 (1973), with edges on Kolar sheets 57G/11 (1975, 1977) and 57H/13 (1973)",
    licence: "CC BY 4.0",
    status: "found",
    links: [{ label: "Open the sheets on Zenodo", href: ZENODO_SOI }],
  },
  {
    id: "ksrsac-wetlands-2023",
    from: 2023,
    when: "2023",
    title: "Wetlands of Bengaluru Urban",
    holder: "Karnataka State Remote Sensing Applications Centre, via OpenCity",
    kind: "map",
    tells: "265 wetland outlines, without names.",
    coverage: "Bengaluru Urban",
    licence: "Public domain",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "kgis-wetlands" }],
  },
  {
    id: "osm-2026",
    from: 2026,
    when: "2026",
    title: "OpenStreetMap water areas",
    holder: "OpenStreetMap contributors",
    kind: "map",
    tells: "Lake outlines drawn by volunteers, and Kannada names.",
    coverage: "Around Bengaluru",
    licence: "ODbL 1.0",
    status: "on-site",
    links: [{ label: "Open OpenStreetMap", key: "osm-2026-09" }],
  },
  {
    id: "atree-lakes",
    when: "No year on record",
    title: "Map of lakes in Bengaluru Urban and Rural districts",
    holder: "ATREE-CSEI, from the BBMP lake master list",
    kind: "map",
    tells: "Each lake's outline, the shape this site draws.",
    coverage: "1,350 lakes",
    licence: "CC BY",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "atree-lakes" }],
  },
  {
    id: "kgis-tanks-ponds",
    when: "No year on record",
    title: "Bengaluru Urban lake and pond maps",
    holder: "Karnataka State Remote Sensing Applications Centre, via OpenCity",
    kind: "map",
    tells: "Outlines for lakes the ATREE map does not draw.",
    coverage: "Bengaluru Urban",
    licence: "Public domain",
    status: "on-site",
    links: [
      { label: "Open the lake map", key: "kgis-tanks" },
      { label: "Open the pond map", key: "kgis-ponds" },
    ],
  },
  {
    id: "land-records-lake-maps",
    when: "No year on record",
    title: "Lake maps, digital and survey",
    holder: "Department of Survey, Settlement and Land Records, Karnataka",
    kind: "map",
    tells: "The official map of each lake, by village and survey number.",
    coverage: "Bengaluru Urban and Bengaluru Rural",
    licence: "Not stated",
    status: "on-site",
    links: [
      { label: "Open the digital maps", key: "landrecords-lake-digital" },
      { label: "Open the survey maps", key: "landrecords-lake-survey" },
    ],
  },
];
