import type { TimelineSource } from "./types";

/** Reports, lists and the records we know of but cannot read. */
export const REPORTS: TimelineSource[] = [
  {
    id: "rau-committee-1986",
    from: 1986,
    when: "1986",
    title: "Lakshman Rau Expert Committee report",
    holder: "India Water Portal",
    kind: "report",
    tells: "Each tank's name, size in hectares, condition, land use and what the committee recommended.",
    coverage: "127 city tanks and 262 green belt tanks",
    licence: "No licence stated",
    status: "on-site",
    links: [{ label: "Open the report (PDF)", key: "rau-1986" }],
  },
  {
    id: "district-gazetteer-1990",
    from: 1990,
    when: "1990",
    title: "Bangalore District Gazetteer",
    kind: "report",
    tells: "What it records about each lake is not known.",
    coverage: "Bangalore District",
    licence: "Not known",
    status: "not-public",
    access: "Not found online",
    links: [],
  },
  {
    id: "lda-list-2002",
    from: 2002,
    when: "2002",
    title: "Lake Development Authority list",
    holder: "Lake Development Authority",
    kind: "report",
    tells: "The authority's list of lakes; what it records about each one is not known.",
    coverage: "Not known",
    licence: "Not known",
    status: "not-public",
    access: "Not found online",
    links: [],
  },
  {
    id: "ramaswamy-committee-2007",
    from: 2007,
    when: "2007",
    title: "A. T. Ramaswamy committee on land encroachment",
    holder: "OpenCity",
    kind: "report",
    tells: "How a few tanks were encroached, case by case.",
    coverage: "The city",
    licence: "Public domain",
    status: "found",
    links: [
      {
        label: "Open on OpenCity",
        href: "https://data.opencity.in/dataset/encorachment-of-government-lands-in-bangalore-city-urban-district-2007",
      },
    ],
  },
  {
    id: "patil-committee-2011",
    from: 2011,
    when: "2011",
    title: "Justice N. K. Patil committee report, lakes PIL",
    holder: "OpenCity",
    kind: "report",
    tells: "Findings on 386 lakes; the annexes with each lake's details are not found.",
    coverage: "1,300 sq km",
    licence: "Not stated",
    status: "found",
    access: "Main text only",
    links: [
      {
        label: "Open the report (PDF)",
        href: "https://data.opencity.in/dataset/46dffdd5-1b51-4a72-bdc0-41a0ec85c31c/resource/225ab3a3-e767-4b63-a406-7048712d6b46/download/0634635f-5928-4030-aaea-d125e488aec2.pdf",
      },
    ],
  },
  {
    id: "mines-geology-2011",
    from: 2011,
    when: "2011",
    title: "Bangalore lakes water quality results",
    holder: "Department of Mines and Geology, Karnataka",
    kind: "report",
    tells: "What was in a lake's water when it was tested in 2011.",
    coverage: "The lakes tested",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "dmg-2011" }],
  },
  {
    id: "koliwad-committee",
    from: 2014,
    to: 2017,
    when: "2014 to 2017",
    title: "Koliwad legislature committee full report, in Kannada",
    holder: "OpenCity",
    kind: "report",
    tells: "Each lake's survey number, how much was encroached, by whom and for what.",
    coverage: "Bengaluru and surrounding lakes",
    licence: "Not stated",
    status: "found",
    access: "273 pages in a legacy Kannada font encoding",
    links: [{ label: "Open on OpenCity", href: "https://data.opencity.in/dataset/bangalore-rural-urban-tanks-report" }],
  },
  {
    id: "lakes-water-quality-2015",
    from: 2015,
    when: "2015",
    title: "Bangalore lakes water quality",
    kind: "report",
    tells: "What was in a lake's water when it was tested in 2015.",
    coverage: "The lakes tested",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "lakes-2015" }],
  },
  {
    id: "jakkur-2016",
    from: 2016,
    when: "2016",
    title: "Jakkur Lake analysis",
    kind: "report",
    tells: "What was in Jakkur Lake's water through 2016.",
    coverage: "Jakkur Lake",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "jakkur-2015" }],
  },
  {
    id: "empri-inventory-2018",
    from: 2018,
    when: "2018",
    title: "Lake inventory of the Bengaluru Metropolitan Area",
    holder: "Environmental Management and Policy Research Institute",
    kind: "report",
    tells: "Whether each lake was still there, and its extent, condition and encroachment.",
    coverage: "1,521 water bodies",
    licence: "Public domain",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "empri-2018" }],
  },
  {
    id: "neeri-2019",
    from: 2019,
    to: 2020,
    when: "2019-20",
    title: "CSIR-NEERI report on Bengaluru lakes",
    holder: "CSIR-NEERI, via OpenCity",
    kind: "report",
    tells: "Each lake's encroachment, boundary, inlets and water quality.",
    coverage: "210 city lakes",
    licence: "Public domain",
    status: "found",
    access: "Scanned, needs text recognition",
    links: [{ label: "Open on OpenCity", href: "https://data.opencity.in/dataset/neeri-report-on-lakes-in-bengaluru-2020" }],
  },
  {
    id: "nwmp-2021",
    from: 2021,
    when: "2021",
    title: "Water quality of lakes and ponds, national monitoring",
    holder: "Central Pollution Control Board",
    kind: "report",
    tells: "What was in a lake's water when it was tested in 2021.",
    coverage: "The lakes tested",
    licence: "Public domain",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "nwmp-2021" }],
  },
  {
    id: "lake-groups-2022",
    from: 2022,
    when: "2022",
    title: "Lake groups in Bengaluru",
    holder: "Citizen Matters",
    kind: "report",
    tells: "Which residents' groups work on a lake.",
    coverage: "Bengaluru",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open the directory (PDF)", key: "citizenmatters-lake-groups-2022" }],
  },
  {
    id: "kspcb-monthly",
    from: 2023,
    to: 2026,
    when: "July 2023 to July 2026",
    title: "Monthly water quality of Bengaluru lakes",
    holder: "Karnataka State Pollution Control Board",
    kind: "report",
    tells: "A lake's water quality class, month by month.",
    coverage: "Lakes with a monitoring station",
    licence: "Not stated",
    status: "on-site",
    links: [
      { label: "Open the July 2026 report", key: "kspcb-2026-07" },
      { label: "Open the July 2023 report", key: "kspcb-2023-07" },
    ],
  },
  {
    id: "ktcda-list-2024",
    from: 2024,
    when: "2024",
    title: "List of lakes in Bengaluru",
    holder: "Karnataka Tank Conservation and Development Authority",
    kind: "report",
    tells: "Which agency looks after each lake.",
    coverage: "The city",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open the list", key: "ktcda-lakes-2024" }],
  },
  {
    id: "encroachment-surveys-2024",
    from: 2024,
    to: 2026,
    when: "2024 to 2026",
    title: "BBMP and Greater Bengaluru Authority encroachment surveys",
    holder: "BBMP and Greater Bengaluru Authority",
    kind: "report",
    tells: "How much of each lake is encroached.",
    coverage: "210 lakes",
    licence: "Not known",
    status: "not-public",
    access: "Known only from affidavits and news",
    links: [],
  },
  {
    id: "minor-irrigation-tanks-2026",
    from: 2026,
    when: "2026",
    title: "Karnataka Minor Irrigation tank list",
    holder: "National Water Data Portal",
    kind: "report",
    tells: "Each tank's name, village, water spread and capacity, but not its location or year.",
    coverage: "146 tanks in both districts",
    licence: "Not stated",
    status: "found",
    access: "Open CSV",
    links: [{ label: "Open the list", href: "https://nwdp.nwic.gov.in/dataset/karnataka-minor-irrigation-tank" }],
  },
  {
    id: "bbmp-custody",
    when: "No year on record",
    title: "Lakes in BBMP custody",
    holder: "BBMP, via OpenCity",
    kind: "report",
    tells: "Who looks after each lake, and its extent on land records.",
    coverage: "Lakes in BBMP custody",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open on OpenCity", key: "bbmp-custody" }],
  },
  {
    id: "bbmp-lake-monitoring",
    when: "No year on record",
    title: "Lakes Monitoring System",
    holder: "BBMP Lakes Division",
    kind: "report",
    tells: "Where each city lake is, with a page for each one.",
    coverage: "City lakes",
    licence: "Not stated",
    status: "on-site",
    links: [{ label: "Open the monitoring site", key: "bbmp-lms" }],
  },
  {
    id: "wetlands-authority-inventory",
    when: "No year on record",
    title: "Wetlands Authority Karnataka inventory",
    holder: "Wetlands Authority Karnataka",
    kind: "report",
    tells: "An entry for each of 16,700 water bodies.",
    coverage: "16,700 water bodies",
    licence: "Not known",
    status: "not-public",
    access: "Behind a login",
    links: [],
  },
  {
    id: "national-wetland-atlas",
    when: "No year on record",
    title: "National Wetland Atlas, tables for each lake",
    kind: "report",
    tells: "What it records about each lake is not known.",
    coverage: "Not known",
    licence: "Not known",
    status: "not-public",
    access: "Not found online",
    links: [],
  },
];
