import { NOW } from "./gaps";
import type { TimelineSource } from "./types";

export const SATELLITES: TimelineSource[] = [
  {
    id: "corona",
    from: 1960,
    to: 1972,
    when: "1960 to 1972",
    title: "CORONA declassified satellite photos",
    holder: "USGS EarthExplorer",
    kind: "satellite",
    tells: "Water, a dry bed or buildings on one date, down to ponds under an acre.",
    coverage: "Frames over Bangalore exist; a 1965 frame was used in a 2019 study",
    licence: "Not stated",
    status: "found",
    access: "Free if already scanned, otherwise $30 a frame",
    links: [],
  },
  {
    id: "hexagon",
    from: 1971,
    to: 1984,
    when: "1971 to 1984",
    title: "HEXAGON declassified satellite photos",
    holder: "USGS",
    kind: "satellite",
    tells: "Water, a dry bed or buildings on one date, at 0.6 to 1.2 m.",
    coverage: "Frames over Bangalore unconfirmed",
    licence: "Not stated",
    status: "found",
    access: "$30 a scene to scan",
    links: [],
  },
  {
    id: "landsat-mss",
    from: 1972,
    to: 1981,
    when: "1972 to 1981",
    title: "Landsat MSS, 60 m",
    holder: "Google Earth Engine",
    kind: "satellite",
    tells: "Whether a lake held water, for lakes over about 8 acres.",
    coverage: "46 scenes, 11 under 20% cloud",
    licence: "Public domain",
    status: "found",
    links: [],
  },
  {
    id: "jrc-surface-water",
    from: 1984,
    to: 2021,
    when: "1984 to 2021",
    title: "Global Surface Water",
    holder: "European Commission Joint Research Centre and Google",
    kind: "satellite",
    tells: "Whether a lake held water each year, for lakes over about 2 acres.",
    coverage:
      "Everywhere. The 1984 to 2024 summary is on the site too; the yearly files for 2022 to 2024 cannot be downloaded yet",
    licence: "CC BY 4.0",
    status: "on-site",
    links: [
      { label: "Open the yearly files, 1984 to 2021", key: "jrc-gsw-1-4-yearly" },
      { label: "Open the download page", key: "jrc-gsw-1-5" },
    ],
  },
  {
    id: "bhuvan-wbis",
    from: 2012,
    to: NOW,
    when: "2012 to now",
    title: "Water Bodies Information System",
    holder: "ISRO Bhuvan",
    kind: "satellite",
    tells: "How far a lake's water spread, month by month or more often.",
    coverage: "Water bodies over 2 ha, and over 1 ha since 2022",
    licence: "Not stated",
    status: "found",
    access: "Public, one lake at a time, no bulk download",
    links: [{ label: "Open the portal", href: "https://bhuvan-wbis.nrsc.gov.in/" }],
  },
  {
    id: "dynamic-world",
    from: 2015,
    to: NOW,
    when: "2015 to now",
    title: "Dynamic World, 10 m",
    holder: "Google Earth Engine",
    kind: "satellite",
    tells: "The chance of water in each image, for ponds over about a quarter acre.",
    coverage: "Everywhere",
    licence: "CC BY 4.0",
    status: "found",
    links: [
      {
        label: "Open in the Earth Engine catalog",
        href: "https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_DYNAMICWORLD_V1",
      },
    ],
  },
  {
    id: "esri-land-cover",
    from: 2017,
    to: 2025,
    when: "2017 to 2025",
    title: "Yearly land cover, 10 m",
    holder: "Esri and Impact Observatory",
    kind: "satellite",
    tells: "Whether a lake's bed was water, built on or bare, each year.",
    coverage: "Everywhere; it will carry yearly water past 2021",
    licence: "CC BY 4.0",
    status: "found",
    links: [{ label: "Open the catalog", href: "https://gee-community-catalog.org/projects/S2TSLULC/" }],
  },
  {
    id: "esa-worldcover-2021",
    from: 2021,
    when: "2021",
    title: "WorldCover, 10 m",
    holder: "European Space Agency",
    kind: "satellite",
    tells: "How much land around each lake was built on, trees or water.",
    coverage: "Everywhere",
    licence: "CC BY 4.0",
    status: "on-site",
    links: [{ label: "Open WorldCover", key: "esa-worldcover-2021" }],
  },
  {
    id: "sentinel-2",
    from: 2025,
    to: NOW,
    when: "2025 to 2026",
    title: "Sentinel-2 images",
    holder: "European Space Agency, Copernicus programme",
    kind: "satellite",
    tells: "How much of a lake is open water, floating weed or dry now.",
    coverage: "Everywhere",
    licence: "Copernicus Sentinel data terms, free and open",
    status: "on-site",
    links: [{ label: "Open the image archive", key: "sentinel2-2026-dry" }],
  },
];
